name: Cypress Tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm run build
      - run: npm run start
        working-directory: server
      - run: npm install cypress
        working-directory: root
      - run: npm install simple-ssh
      - run: npm install @cypress/webpack-preprocessor
      - run: npm install cypress-delete-downloads-folder
      - name: Cypress run
        uses: cypress-io/github-action@v6
