name: Cypress Tests

on: push

jobs:
  cypress-run:
    services:
      testbed:
        image: naoso5/openpbs
        ports:
          - 4000:22
    env:
      WHEEL_USE_HTTP: 1
      WHEEL_TEST_REMOTEHOST: testServer
      WHEEL_TEST_REMOTE_PASSWORD: passw0rd
      TZ: JST-9
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - run: mkdir -p ~/.wheel
      - run: >
          echo '[{
            "name": "testServer",
            "host": "localhost",
            "path": "/home/testuser",
            "keyFile": null,
            "username": "testuser",
            "numJob": 5,
            "port": 4000,
            "id": "dummy-id",
            "jobScheduler": "PBSPro",
            "renewInterval": 0,
            "renewDelay": 0,
            "statusCheckInterval": 10,
            "maxStatusCheckError": 10,
            "readyTimeout": 5000
          }]' > ~/.wheel/remotehost.json
      - run: cat ~/.wheel/remotehost.json
      
      - name: Checkout
        uses: actions/checkout@v4
        
      # - name: install cypress report module
      #   run: npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # working-directory: cypress/e2e
          browser: chrome
          record: true
          install: false
          build: npm run build
          start: npm start
          command: |
            npx cypress run
          # command: npm install simple-ssh
          spec: cypress/e2e/spec.cy.js
          
      # - name: cypress report create html
      #   if: always()
      #   run: |
      #     npx mochawesome-merge "cypress/mochawesome*.json" > cypress/merge-report.json
      #     npx marge cypress/merge-report.json -o cypress
      
      - name: Cypress artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          if-no-files-found: ignore
          path: cypress/screenshots/**
